""" Tests for the command line executable. """

import contextlib
import importlib.resources
import io
import os
import shutil
import tempfile
import unittest
from unittest.mock import patch

import tomlkit

from edx_lint.cmd import main
from edx_lint.cmd.write_uv_constraints import _parse_constraints


PYLINTRC = "pylintrc"
PYLINTRC_TWEAKS = "pylintrc_tweaks"
PYLINTRC_BACKUP = "pylintrc_backup"

EDITORCONFIG = ".editorconfig"

JUST_TESTING = "just_for_testing.txt"


@contextlib.contextmanager
def capture_output():
    """
    Capture all of stdout and stderr, and return a StringIO.

    Note: using this means the output doesn't go to the real stdout. If you
    use the -s switch to see output, you won't see output inside this context.

    """
    output = io.StringIO()
    with contextlib.redirect_stdout(output):
        with contextlib.redirect_stderr(output):
            yield output


class CommandTest(unittest.TestCase):
    """Helpers for testing commands."""

    def setUp(self):
        super().setUp()

        # Make a temporary directory to work in, and rm-rf it when we're done.
        tempdir = tempfile.mkdtemp(suffix="_edx_lint_test")
        self.addCleanup(shutil.rmtree, tempdir)

        # Change into the temp directory, and change back when we are done.
        thisdir = os.getcwd()
        self.addCleanup(os.chdir, thisdir)
        os.chdir(tempdir)

        # Assure the file does not already exist.
        self.assert_not_file(PYLINTRC)

    def call_command(self, argv=None):
        """Call an edx_lint script command.

        Arguments:
            argv (list) -- arguments to pass to the edx_lint script
        """
        # This pointless statement is here because removing the statement causes a different warning. Currently we run
        # pylint at multiple versions in the Open edX platform.  However, the other warning (no-self-use) exists in the
        # old version of pylint (pre 2.13.0) but not the new version. This is the only way to fix the warning in a way
        # that will work for both the old and new version.
        self    # pylint: disable=pointless-statement
        return main.main(argv)

    def assert_file(self, filename, contains=None, not_contains=None):
        """Assert that a file exists, and optionally, contains some text."""
        self.assertTrue(os.path.isfile(filename))
        if contains is not None or not_contains is not None:
            with open(filename) as f:
                text = f.read()
                if contains is not None:  # pragma: no branch
                    self.assertIn(contains, text)
                if not_contains is not None:  # pragma: no branch
                    self.assertNotIn(not_contains, text)

    def assert_not_file(self, filename):
        """Assert that a file doesn't exist."""
        self.assertFalse(os.path.isfile(filename))


class WriteCommandTest(CommandTest):
    """Tests for the write command."""

    def test_write_arg_errors(self):
        self.assertEqual(1, self.call_command(["write"]))
        self.assertEqual(2, self.call_command(["write", "xyzzy"]))

    def test_write_creates_pylintrc(self):
        """ Verify the command writes a pylintrc file. """
        # Create the pylintrc.
        self.assertEqual(0, self.call_command(["write", PYLINTRC]))
        self.assert_file(PYLINTRC, contains="*****\n# ** DO NOT EDIT THIS FILE **\n# *****")
        self.assert_file(PYLINTRC, not_contains="you must edit the central file", contains="LOCAL CHANGE")
        self.assert_file(PYLINTRC, contains="\n[MASTER]\n")
        self.assert_file(PYLINTRC, not_contains="\n# \n")

        # Try to create it again, it will verify it.
        self.assertEqual(0, self.call_command(["write", PYLINTRC]))

    def test_write_backups_modified_file(self):
        # Make the pylintrc.
        self.assertEqual(0, self.call_command(["write", PYLINTRC]))
        self.assert_file(PYLINTRC)
        self.assert_not_file(PYLINTRC_BACKUP)

        # Modify it.
        with open(PYLINTRC, "a") as pylintrc:
            pylintrc.write("# modified!\n")

        # Try to write again.
        self.assertEqual(0, self.call_command(["write", PYLINTRC]))
        self.assert_file(PYLINTRC_BACKUP, contains="# modified!")

        # And if we write again, the previous backup is deleted.
        with open(PYLINTRC, "a") as pylintrc:
            pylintrc.write("# changed!\n")
        self.assertEqual(0, self.call_command(["write", PYLINTRC]))
        self.assert_file(
            PYLINTRC_BACKUP, contains="# changed!", not_contains="# modified!"
        )

    def test_write_applies_tweaks(self):
        # Create a tweaks file.
        with open(PYLINTRC_TWEAKS, "w") as tweaks:
            tweaks.write("[MASTER]\nxyzzy = plugh\n")

        # Write the pylintrc.
        self.assertEqual(0, self.call_command(["write", PYLINTRC]))

        # The tweak is in there!
        self.assert_file(PYLINTRC, contains="xyzzy = plugh")

    def test_file_types(self):
        self.assertEqual(0, self.call_command(["write", JUST_TESTING]))
        self.assert_file(JUST_TESTING, contains="\n-- ** DO NOT EDIT")
        self.assert_file(JUST_TESTING, contains="you must edit the central file", not_contains="LOCAL CHANGE")


class UpdateCommandTest(CommandTest):
    """Tests for the update command."""

    def test_no_files_exist(self):
        self.assertEqual(0, self.call_command(["update"]))
        self.assert_not_file(PYLINTRC)
        self.assert_not_file(EDITORCONFIG)

    def test_one_file_exists(self):
        # Write the initial version of pylintrc.
        self.assertEqual(0, self.call_command(["write", PYLINTRC]))
        self.assert_file(PYLINTRC, contains="[MASTER]")
        self.assert_not_file(EDITORCONFIG)

        # Pretend edx-lint has a newer version of pylintrc, and update files.
        with patch("edx_lint.write.get_file_content") as get_file_content:
            get_file_content.return_value = "[xyz]\nsetting = True"
            self.assertEqual(0, self.call_command(["update"]))

        # pylintrc is re-written with new content.
        self.assert_file(PYLINTRC, contains="setting = True")
        self.assert_file(PYLINTRC, not_contains="[MASTER]")
        # .editorconfig still hasn't been written.
        self.assert_not_file(EDITORCONFIG)

    def test_update_backs_up_handwritten_files(self):
        # Create a hand-written pylintrc file:
        with open(PYLINTRC, "w") as pylintrc:
            pylintrc.write("[bogus]\nnot_really = pylintrc\n")

        # Update will see it's not one made by edx-lint, and move it aside.
        self.assertEqual(0, self.call_command(["update"]))

        # The backup file is our original hand-written file.
        self.assert_file(PYLINTRC_BACKUP, contains="not_really = pylintrc")
        # The pylintrc file was written by edx-lint.
        self.assert_file(PYLINTRC, contains="[MASTER]")


class CheckCommandTest(CommandTest):
    """Tests for the `check` command."""

    def test_happy_path(self):
        self.assertEqual(0, self.call_command(["write", PYLINTRC]))
        with capture_output() as output:
            self.assertEqual(0, self.call_command(["check", PYLINTRC]))
        expected = "pylintrc is good\n"
        self.assertEqual(output.getvalue(), expected)

    def test_handwritten_is_ok(self):
        # Create a hand-written pylintrc file:
        with open(PYLINTRC, "w") as pylintrc:
            pylintrc.write("[bogus]\nnot_really = pylintrc\n")

        with capture_output() as output:
            self.assertEqual(0, self.call_command(["check", PYLINTRC]))
        expected = "pylintrc wasn't written by edx_lint\n"
        self.assertEqual(output.getvalue(), expected)

    def test_handedited_fails(self):
        self.assertEqual(0, self.call_command(["write", PYLINTRC]))
        with open(PYLINTRC, "a") as pylintrc:
            pylintrc.write("More stuff by hand\n")

        with capture_output() as output:
            self.assertEqual(1, self.call_command(["check", PYLINTRC]))
        expected = "pylintrc seems to have been edited\n"
        self.assertEqual(output.getvalue(), expected)

    def test_all_files(self):
        self.assertEqual(0, self.call_command(["write", PYLINTRC]))
        self.assertEqual(0, self.call_command(["write", EDITORCONFIG]))

        with capture_output() as output:
            self.assertEqual(0, self.call_command(["check"]))
        expected = (
            "pylintrc is good\n" +
            ".editorconfig is good\n"
        )
        self.assertEqual(output.getvalue(), expected)

    def test_cant_check_a_missing_file(self):
        with capture_output() as output:
            self.assertEqual(2, self.call_command(["check", "xyzzy.foo"]))
        self.assertEqual(output.getvalue(), "xyzzy.foo doesn't exist\n")


PYPROJECT_MINIMAL = '[project]\nname = "test"\n'
# Read the actual bundled constraints so tests stay in sync with the file automatically.
_GLOBAL_CONSTRAINTS_TEXT = (
    importlib.resources.files("edx_lint")
    .joinpath("files/common_constraints.txt")
    .read_text(encoding="utf-8")
)
GLOBAL_CONSTRAINTS, _ = _parse_constraints(_GLOBAL_CONSTRAINTS_TEXT)
# Use the first entry as a representative value for presence checks.
GLOBAL_CONSTRAINT = GLOBAL_CONSTRAINTS[0]


class WriteUvConstraintsCommandTest(CommandTest):
    """Tests for the write_uv_constraints command."""

    def _make_pyproject(self, path="pyproject.toml", content=PYPROJECT_MINIMAL):
        with open(path, "w") as f:
            f.write(content)

    def test_no_args_updates_default(self):
        self._make_pyproject()
        self.assertEqual(0, self.call_command(["write_uv_constraints"]))
        self.assert_file("pyproject.toml", contains=GLOBAL_CONSTRAINT)

    def test_explicit_pyproject_path(self):
        self._make_pyproject("other.toml")
        self.assertEqual(0, self.call_command(["write_uv_constraints", "other.toml"]))
        self.assert_file("other.toml", contains=GLOBAL_CONSTRAINT)

    def test_local_merges_global_and_local(self):
        self._make_pyproject(
            content=PYPROJECT_MINIMAL + '[tool.edx_lint]\nuv_constraints = ["mypackage<2.0"]\n'
        )
        assert self.call_command(["write_uv_constraints"]) == 0
        written = self._read_constraint_dependencies()
        assert GLOBAL_CONSTRAINT in written
        assert "mypackage<2.0" in written

    def test_idempotent(self):
        self._make_pyproject()
        self.assertEqual(0, self.call_command(["write_uv_constraints"]))
        with open("pyproject.toml") as f:
            first = f.read()
        self.assertEqual(0, self.call_command(["write_uv_constraints"]))
        with open("pyproject.toml") as f:
            second = f.read()
        self.assertEqual(first, second)

    def test_preserves_existing_content(self):
        self._make_pyproject(
            content='[project]\nname = "myproject"\nversion = "1.0"\n\n[tool.ruff]\nline-length = 88\n'
        )
        self.assertEqual(0, self.call_command(["write_uv_constraints"]))
        self.assert_file("pyproject.toml", contains='name = "myproject"')
        self.assert_file("pyproject.toml", contains="line-length = 88")
        self.assert_file("pyproject.toml", contains=GLOBAL_CONSTRAINT)

    def test_missing_pyproject_returns_2(self):
        # No pyproject.toml created in temp dir
        with capture_output():
            self.assertEqual(2, self.call_command(["write_uv_constraints"]))

    def test_unknown_args_returns_nonzero(self):
        self._make_pyproject()
        ret = self.call_command(["write_uv_constraints", "--bogus-flag"])
        self.assertNotEqual(0, ret)

    def _read_constraint_dependencies(self, path="pyproject.toml"):
        """Read [tool.uv].constraint-dependencies from a pyproject.toml."""
        with open(path) as f:
            data = tomlkit.load(f)
        return list(data["tool"]["uv"]["constraint-dependencies"])

    def test_local_overrides_global_for_same_package(self):
        # Extract the package name from the first global constraint and write a
        # stricter local version.  The local pin should win.
        first_global = GLOBAL_CONSTRAINTS[0]
        pkg = first_global.split("<")[0].split(">")[0].split("=")[0].split("!")[0].strip()
        local_pin = f"{pkg}==0.0.1"
        self._make_pyproject(
            content=PYPROJECT_MINIMAL + f'[tool.edx_lint]\nuv_constraints = ["{local_pin}"]\n'
        )
        assert self.call_command(["write_uv_constraints"]) == 0
        written = self._read_constraint_dependencies()
        assert local_pin in written
        assert first_global not in written

    def test_deduplicates_exact_duplicates(self):
        # Exact duplicate in [tool.edx_lint].uv_constraints should appear only once.
        self._make_pyproject(
            content=PYPROJECT_MINIMAL + f'[tool.edx_lint]\nuv_constraints = ["{GLOBAL_CONSTRAINTS[0]}"]\n'
        )
        assert self.call_command(["write_uv_constraints"]) == 0
        written = self._read_constraint_dependencies()
        assert written.count(GLOBAL_CONSTRAINTS[0]) == 1
